# Generated by Django 4.1.3 on 2022-12-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('attributes', models.ManyToManyField(to='anon.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('k', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('value', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Edge',
            fields=[
                ('rel_edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.relationship')),
                ('owner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to='anon.owner')),
                ('owner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner2', to='anon.owner')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.provider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='relationships',
            field=models.ManyToManyField(to='anon.relationship'),
        ),
        migrations.CreateModel(
            name='Attribute_Edge',
            fields=[
                ('attr_edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.attribute')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.owner')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.value')),
            ],
        ),
    ]
