# Generated by Django 4.1.3 on 2022-12-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='anon.attribute'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='relationships',
            field=models.ManyToManyField(blank=True, to='anon.relationship'),
        ),
    ]
