# Generated by Django 3.2.16 on 2023-01-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0002_alter_campaign_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonyGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calgo', models.CharField(default='error', max_length=20)),
                ('enforcer', models.CharField(default='error', max_length=20)),
                ('ail', models.FloatField()),
                ('rru', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, to='anon.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='anonygraph',
            constraint=models.UniqueConstraint(fields=('campaign', 'calgo', 'enforcer'), name='unique_campaign_calgo_enforcer_combination'),
        ),
    ]
