# Generated by Django 3.2.16 on 2023-02-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0003_auto_20230111_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='campaign',
        ),
        migrations.AddField(
            model_name='attribute_edge',
            name='campaign',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, to='anon.campaign'),
        ),
        migrations.AddField(
            model_name='owner',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='anon.Campaign'),
        ),
        migrations.AddField(
            model_name='relationship_edge',
            name='campaign',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, to='anon.campaign'),
        ),
    ]
