# Generated by Django 3.2.16 on 2023-02-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0004_auto_20230207_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='attribute_edge',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='relationship_edge',
            name='campaign',
        ),
        migrations.AddField(
            model_name='owner',
            name='campaign',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, to='anon.campaign'),
        ),
    ]
