# Generated by Django 3.2.16 on 2023-02-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0005_auto_20230207_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='campaign',
            field=models.ForeignKey(default='Person', on_delete=django.db.models.deletion.CASCADE, to='anon.campaign'),
        ),
    ]
