# Generated by Django 3.2.16 on 2023-02-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0007_auto_20230207_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCampaign',
            fields=[
                ('owner_campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('k', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='k',
        ),
        migrations.AddField(
            model_name='ownercampaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon.owner'),
        ),
        migrations.AddConstraint(
            model_name='ownercampaign',
            constraint=models.UniqueConstraint(fields=('owner', 'campaign'), name='unique_campaign_owner_combination'),
        ),
    ]
